### ISSUE TITLE
Can't create new activities in Android Studio on mac

### ISSUE THREAD

**Issue by llunn** [NicholasBarreyre/SEProject#17]
Trying to create a new activity in Android Studio v3.0.1 on Macbook gives IDE error.

**Comment by znwilkins** [comment]
See 9b70a771b281d580864cddf0355b501adf25e948 for (unconfirmed) fix.

**Comment by znwilkins** [comment]
Note: [This was helpful.](https://issuetracker.google.com/issues/37132650)

The issue occurs when Android Studio is installed on a drive other than C (under Windows). As a result, it tries to run Gradle from a different location than the default. Switching back to the default Gradle wrapper removes the error on my system.

**Comment by llunn** [comment]
@znwilkins I think there are a number of other issues hiding here with the intellij project files.  For example, if you look in the gradle.xml file it has other paths specific to my machine.  I will spend some time hunting around for solutions.

**Comment by llunn** [comment]
@znwilkins I think we should start by swapping our current .gitignore with [this] (https://github.com/github/gitignore/blob/master/Android.gitignore) template for android apps from the github team.

For the modules.xml issue, i see two options:

1. Add `.idea/modules.xml` to the gitignore file.  

While this is not ideal, since modules.xml defines logical components of a project, I think it will be fine for this project since we will unlikely be adding additional modules on top of the app module.  This file contains the 'root module' which is named the same as the directory that checked out files from github are being saved.  So long as we each set this value correctly and do not version control the file it should resolve the issue.

2. Add a Path Variable to Intellij and version control the module.xml file with the line:
` <module fileurl="file://$PROJECT_DIR$/$SEPROJECT_ROOT$.iml" filepath="$PROJECT_DIR$/$SEPROJECT_ROOT$.iml" />`  replacing the line  ` <module fileurl="file://$PROJECT_DIR$/github.iml" filepath="$PROJECT_DIR$/github.iml" />`

The SEPROJECT_ROOT path variable would have a value equal to the folder that the files are checked out to.  For example, on my machine: SEPROJECT_ROOT="github".

To add a path variable, go to File | Settings | Appearance & Behaviour | Path Variables.  Click the green plus sign, and enter SEPROJECT_ROOT for name, and your source folder for value.

The downside to this option is that path variables are Intellij wide and it must be set for anyone checking out code.  I think it is a better alternative than option 1 since it abstracts the specific issue of where one stores project files on their computers to an development environment setting, yet still allows version controlled module management inside the root folder if we wanted to add more in the future.

I believe changing the .gitignore and this modules.xml issue will fix the issue with not being able to make new activities.

**Comment by znwilkins** [comment]
@llunn Neither of these suggestions work, unfortunately. The problem is with Gradle, and so changing to the default Gradle wrapper seems to be the only thing that does the job.
