### ISSUE TITLE
Edit User Information screen crashes with blank info

### ISSUE THREAD

**Issue by nickburris** [NicholasBarreyre/SEProject#27]
On a new account with no user information, if you click the User Info button from the main screen, then click the edit button in the bottom right, don't enter any info in, then click the save button, the app crashes. It should return to the default values. 

This is probably a simple fix; when the user edits user information data, for each of the fields, if they're blank, return to default values.

Assigning to original author @znwilkins, feel free to reassign.

**Comment by znwilkins** [comment]
Argh, thanks for finding this. I will take care of it!
