### ISSUE TITLE
Fix back button behaviour for all Activities

### ISSUE THREAD

**Issue by nickburris** [NicholasBarreyre/SEProject#28]
Pressing the Android back button does not behave naturally. This is because, by default, the back button goes to the last activity, but this is not always desired. 

For example, if you go to the Exercises screen, create an exercise (taking you to the CreateExercise activity), submit it (returning you to the Exercises activity), then press the back button, you'd expect that to take you to the main activity, but it returns you to the previous activity where you were creating the exercise. This arises in other parts of the app too, and makes it difficult to use.

https://developer.android.com/training/implementing-navigation/temporal.html

I can do this next week, unless someone wants to do it sooner then feel free to take it (just assign yourself to this github issue so I know).

**Comment by DarbyshireE** [comment]
https://stackoverflow.com/a/3008684

**Comment by znwilkins** [comment]
This has been fixed.
