### ISSUE TITLE
Fix Android Studio's test coverage report and identify problem areas

### ISSUE THREAD

**Issue by nickburris** [NicholasBarreyre/SEProject#39]
Android Studio does not report test coverage properly currently, because it only reports coverage by unit tests, not the instrumented (espresso) tests, which do most of our testing. Once it considers our espresso tests as coverage we'll have a more accurate number. This may be helpful: https://stackoverflow.com/questions/33393871/how-to-obtain-coverage-for-android-project-using-espresso-tests

Once that's working, we can identify what areas of our code need better test coverage.

**Comment by llunn** [comment]
The local code coverage changes are working.  However, Espresso tests on CircleCI 2.0 seems to be a no go according to https://circleci.com/docs/2.0/language-android/

I tried the solution offered on medium.com did not work: https://medium.com/android-testing-daily/running-espresso-tests-on-circle-ci-ec919f85a116

Considering the current workload, I recommend pulling the local code coverage changes in and addressing the CircleCI instrumentation tests at a later time.
